# Generated by Django 4.2.4 on 2023-08-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=25)),
                ('epaciente', models.CharField(max_length=250)),
                ('emedico', models.CharField(max_length=250)),
                ('edistri', models.CharField(max_length=250)),
                ('ecolor', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
