# Generated by Django 4.2.4 on 2023-09-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=250)),
                ('proveedore', models.CharField(max_length=250)),
                ('contacto_tel', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
    ]
